### ISSUE TITLE
Fails to restore 5th generation iPad (iPad 2017)

### ISSUE THREAD

**Issue by EAG08** [libimobiledevice/idevicerestore#160]
Attempting to restore the latest iPad (Released March 24th, 2017) exits with code 255 and results in:

    ERROR: Unable to discover device model

Here is information of an iPad  of this model gathered with ideviceinfo:

```
ActivationState: Activated
BasebandStatus: NoTelephonyCapabilty
BoardId: 16
BrickState: false
BuildVersion: 14E277
CPUArchitecture: arm64
ChipID: 32768
DeviceClass: iPad
DeviceColor: 2
DeviceName: iPad
FirmwareVersion: iBoot-3406.50.244
HardwareModel: J71sAP
HardwarePlatform: s8000
HasSiDP: true
HostAttached: true
ModelNumber: MPGW2
NonVolatileRAM: 
 auto-boot: dHJ1ZQ==
 backlight-level: MTUyNw==
 boot-args: 
 bootdelay: MA==
PartitionType: GUID_partition_scheme
PasswordProtected: false
ProductName: iPhone OS
ProductType: iPad6,11
ProductVersion: 10.3
ProductionSOC: true
ProtocolVersion: 2
RegionInfo: LL/A
SBLockdownEverRegisteredKey: false
SIMStatus: kCTSIMSupportSIMStatusReady
SoftwareBehavior: EQAAAAAAAAAAAAAAAAAAAA==
SoftwareBundleVersion: 
SupportedDeviceFamilies[2]: 
 0: 1
 1: 2
TelephonyCapability: false
TimeIntervalSince1970: 1492125216.992325
TimeZone: US/Pacific
TimeZoneOffsetFromUTC: -25200.000000
TrustedHostAttached: true
UseRaptorCerts: true
Uses24HourClock: false
```
